### ISSUE TITLE
Can't send message with pika [code]

### ISSUE THREAD

**Issue by japrogramer** [kalaspuff/tomodachi#682]
The service im defining in tomodachi is quite basic
```
from aiopg.sa import create_engine
from typing import Any, Dict
from tomodachi.protocol import JsonBase
from config.settings import settings

import tomodachi
import os


@tomodachi.service
class Service(tomodachi.Service):
    name = 'example'
    log_level = 'INFO'
    uuid = os.environ.get('SERVICE_UUID')
    message_protocol = JsonBase
    options = {
        'amqp': {
            'host': 'rabbit',
            'login': os.environ.get('RABBITMQ_DEFAULT_USER'),
            'password': os.environ.get('RABBITMQ_DEFAULT_PASS'),
            }
        }

    # A route / topic on which the service will subscribe to via AMQP (or AWS SNS/SQS)
    @tomodachi.amqp('example.topic')
    async def example_topic_func(self, message: Any) -> None:
        self.log('Received data - "{}"'.format(message))
        # Received message, sending same message as response on another route / topic
        # await tomodachi.amqp_publish(self, message, routing_key='example.response')

    @tomodachi.amqp('example.#')
    async def wildcard_route(self, metadata: Dict, data: Any) -> None:
        if settings.DEBUG:
            self.log(
                'Received data (function: wildcard_route, topic: {}) - "{}"'\
                .format(metadata.get('topic', ''), data))

    async def _started_service(self) -> None:
        db_config = settings.DB_CONFIG
        eng = await create_engine(**db_config)
        self.pgeng = eng

        async def publish(data: Any, routing_key: str) -> None:
            self.log('Publish data "{}"'.format(data))
            await tomodachi.amqp_publish(self, data, routing_key=routing_key)

        await publish('test', 'example.topic')
        await publish('友達', 'example.route1')
        await publish('other data', 'example.route2')
```

aiopika code 

```
import asyncio
import aio_pika
from aio_pika import connect, Message, DeliveryMode, ExchangeType
# import the logging library
import logging
logger = logging.getLogger("asyncio")
#logger.setLevel(logging.WARNING)


async def main():
    logger.info('aquiring connection')
    connection = await aio_pika.connect_robust(
        "amqp://rabbitmq:rabbitmq@rabbit/")

    async with connection:
        print('test')
        channel = await connection.channel()
        routing_key = 'example.topic'

        channel_exchange = 'amqp.topic'
        example = await channel.declare_exchange(
            channel_exchange, ExchangeType.FANOUT
            )

        logger.info('publishing message')
        hello = await example.publish(
            aio_pika.Message(
                body='Hello '.encode(),#.format(routing_key).encode(),
                delivery_mode=DeliveryMode.PERSISTENT,
            ),
            routing_key=routing_key
        )
        # hello = await channel.default_exchange.publish(
            # aio_pika.Message(
                # body='Hello '.encode(),#.format(routing_key).encode(),
                # delivery_mode=DeliveryMode.PERSISTENT,
            # ),
            # routing_key=routing_key
        # )
    return hello


if __name__ == "__main__":
    asyncio.run(main())
```
But the data isn't received by the service
```
Starting services...

tomodachi/0.13.7
November 19, 2018 - 07:47:52,122597
Quit services with <ctrl+c>.
2018-11-19 07:47:52,227 (services.main): Initializing service "example" [id: b8dd3acc-d6ef-415d-b5eb-ac6a69635f56]
2018-11-19 07:47:52,260 (services.main): Started service "example" [id: b8dd3acc-d6ef-415d-b5eb-ac6a69635f56]
2018-11-19 07:47:52,265 (log.example): Publish data "test"
2018-11-19 07:47:52,265 (log.example): Publish data "友達"
2018-11-19 07:47:52,266 (log.example): Publish data "other data"
2018-11-19 07:47:52,268 (log.example): Received data - "{'service': {'name': 'example', 'uuid': 'b8dd3acc-d6ef-415d-b5eb-ac6a69635f56'}, 'metadata': {'message_uuid': 'b8dd3acc-d6ef-415d-b5eb-ac6a69635f56.670d3b8a-7661-4fb4-bdcd-9374621f74a6', 'protocol_version': 'tomodachi-json-base--1.0.0', 'timestamp': 1542613672.2656496, 'topic': 'example.topic', 'data_encoding': 'raw'}, 'data': 'test'}"
2018-11-19 07:47:52,269 (log.example): Received data (function: wildcard_route, topic: example.topic) - "test"
2018-11-19 07:47:52,269 (log.example): Received data (function: wildcard_route, topic: example.route1) - "友達"
2018-11-19 07:47:52,270 (log.example): Received data (function: wildcard_route, topic: example.route2) - "other data"
```

```
/ # rabbitmqctl list_bindings
Listing bindings for vhost /...
        exchange        53689b8a74df7f332a3c7ad8e7203e1260383f438cc00f38a8611d20e132b992        queue   53689b8a74df7f332a3c7ad8e7203e1260383f438cc00f38a8611d20e132b992        []
        exchange        92fe559887f5718130bda062c95fd3689e9bf0cfdb3fe4cdd06634521b37668d        queue   92fe559887f5718130bda062c95fd3689e9bf0cfdb3fe4cdd06634521b37668d        []
        exchange        94190a0b6168bf8f71dac6d2a99d966e354acf5d2aba6a5fdc2f841eaf0629dd        queue   94190a0b6168bf8f71dac6d2a99d966e354acf5d2aba6a5fdc2f841eaf0629dd        []
        exchange        a4eee34f58e01902794b4deebc1a0641e9d31165c93581318b35fa57591d656e        queue   a4eee34f58e01902794b4deebc1a0641e9d31165c93581318b35fa57591d656e        []
        exchange        d11e8ad0d3205851de20f0ba1a07d7a6e83b712d8b84cd6794298d292f8d1f48        queue   d11e8ad0d3205851de20f0ba1a07d7a6e83b712d8b84cd6794298d292f8d1f48        []
        exchange        e709da337f061c09134781ccbbab084bbef3e4ed5e0f28012c704aa6d224d216        queue   e709da337f061c09134781ccbbab084bbef3e4ed5e0f28012c704aa6d224d216        []
amq.topic       exchange        94190a0b6168bf8f71dac6d2a99d966e354acf5d2aba6a5fdc2f841eaf0629dd        queue   example.#       []
amq.topic       exchange        a4eee34f58e01902794b4deebc1a0641e9d31165c93581318b35fa57591d656e        queue   example.#       []
amq.topic       exchange        d11e8ad0d3205851de20f0ba1a07d7a6e83b712d8b84cd6794298d292f8d1f48        queue   example.#       []
amq.topic       exchange        53689b8a74df7f332a3c7ad8e7203e1260383f438cc00f38a8611d20e132b992        queue   example.topic   []
amq.topic       exchange        92fe559887f5718130bda062c95fd3689e9bf0cfdb3fe4cdd06634521b37668d        queue   example.topic   []
amq.topic       exchange        e709da337f061c09134781ccbbab084bbef3e4ed5e0f28012c704aa6d224d216        queue   example.topic   []
/ #


```

**Comment by kalaspuff** [comment]
I can try this out a bit later. I'm not sure if RabbitMQ differs between exchanges `amq.topic` (which tomodachi uses by default) and the `amqp.topic` exchange which you've specified in the pika code or if they're aliased.

https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges

I would suggest to try to change `amqp.topic` to `amq.topic` first and see if that helps at least.

**Comment by japrogramer** [comment]
@kalaspuff thanks for the tip I managed to get my message to be sent but now im receiving an error at the tomodachi service.

```
import asyncio
import aio_pika
from aio_pika import connect, Message, DeliveryMode, ExchangeType
# import the logging library
import logging
logger = logging.getLogger("asyncio")
#logger.setLevel(logging.WARNING)


async def main():
    logger.info('aquiring connection')
    connection = await aio_pika.connect_robust(
        "amqp://rabbitmq:rabbitmq@rabbit/")

    async with connection:
        print('test')
        channel = await connection.channel()
        routing_key = 'example.topic'
        message = aio_pika.Message(
            body='Hello '.encode(),#.format(routing_key).encode(),
            # delivery_mode=DeliveryMode.PERSISTENT,
            )

        await exchange(channel, message, routing_key)

        # hello = await channel.default_exchange.publish(
            # message,
            # routing_key=routing_key
        # )
    # return hello


async def exchange(channel, message, routing_key):
        channel_exchange = 'amq.topic'
        queue = await channel.declare_queue(
            routing_key,
            durable=True
        )
        example = await channel.declare_exchange(
            channel_exchange,
            ExchangeType.TOPIC,
            durable=True
            )

        logger.info('publishing message')
        hello = await example.publish(
            message,
            routing_key=routing_key
        )


if __name__ == "__main__":
    asyncio.run(main())
```

```
tomodachi/0.13.7
November 29, 2018 - 07:33:44,484976
Quit services with <ctrl+c>.
2018-11-29 07:33:44,759 (services.main): Initializing service "example" [id: 129f2293-1636-4dd2-a3bb-892e8c5ffeb9]
2018-11-29 07:33:44,795 (services.main): Started service "example" [id: 129f2293-1636-4dd2-a3bb-892e8c5ffeb9]
2018-11-29 07:33:44,802 (log.example): Publish data "test"
2018-11-29 07:33:44,803 (log.example): Publish data "友達"
2018-11-29 07:33:44,803 (log.example): Publish data "other data"
2018-11-29 07:33:44,806 (log.example): Received data (function: wildcard_route, topic: example.topic) - "test"
2018-11-29 07:33:44,807 (log.example): Received data - "{'service': {'name': 'example', 'uuid': '129f2293-1636-4dd2-a3bb-892e8c5ffeb9'}, 'metadata': {'message_uuid': '129f2293-1636-4dd2-a3bb-892e8c5ffeb9.69c8def0-c315-4d77-bb79-9942d3468abe', 'protocol_version': 'tomodachi-json-base--1.0.0', 'timestamp': 1543476824.802985, 'topic': 'example.topic', 'data_encoding': 'raw'}, 'data': 'test'}"
2018-11-29 07:33:44,808 (log.example): Received data (function: wildcard_route, topic: example.route1) - "友達"
2018-11-29 07:33:44,808 (log.example): Received data (function: wildcard_route, topic: example.route2) - "other data"
2018-11-29 07:33:50,846 (exception): Uncaught exception: Expected object or value
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tomodachi/transport/amqp.py", line 135, in handler
    message, message_uuid, timestamp = await parse_message_func(payload)
  File "/usr/local/lib/python3.7/site-packages/tomodachi/protocol/json_base.py", line 38, in parse_message
    message = ujson.loads(payload)
ValueError: Expected object or value
2018-11-29 07:33:50,848 (exception): Uncaught exception: Expected object or value
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tomodachi/transport/amqp.py", line 135, in handler
    message, message_uuid, timestamp = await parse_message_func(payload)
  File "/usr/local/lib/python3.7/site-packages/tomodachi/protocol/json_base.py", line 38, in parse_message
    message = ujson.loads(payload)
ValueError: Expected object or value
```

**Comment by japrogramer** [comment]
i managed to get the data to send by using a string quoted json object but than this happens
```
2018-11-29 08:00:58,529 (exception): Uncaught exception: local variable 'data' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tomodachi/transport/amqp.py", line 135, in handler
    message, message_uuid, timestamp = await parse_message_func(payload)
  File "/usr/local/lib/python3.7/site-packages/tomodachi/protocol/json_base.py", line 61, in parse_message
    'data': data
UnboundLocalError: local variable 'data' referenced before assignment
2018-11-29 08:00:58,530 (exception): Uncaught exception: local variable 'data' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tomodachi/transport/amqp.py", line 135, in handler
    message, mess
```
